var modules =
[
    [ "Speckle Variance Contrast Processing", "group___speckle_variance.html", "group___speckle_variance" ],
    [ "Error Handling", "group___error_handling.html", "group___error_handling" ],
    [ "Data Access", "group___data.html", "group___data" ],
    [ "Data Creation and Clearing", "group___data_creation.html", "group___data_creation" ],
    [ "Hardware", "group___hardware.html", "group___hardware" ],
    [ "Internal Values", "group___internal.html", "group___internal" ],
    [ "Pattern Factory/Probe", "group___probe.html", "group___probe" ],
    [ "Scan Pattern", "group___scan_pattern.html", "group___scan_pattern" ],
    [ "Mathematical manipulations", "group___math.html", "group___math" ],
    [ "Acquisition", "group___acquisition.html", "group___acquisition" ],
    [ "Processing", "group___processing.html", "group___processing" ],
    [ "Export and Import", "group___import_export.html", "group___import_export" ],
    [ "Volume", "group___volume.html", "group___volume" ],
    [ "ProbeCalibration", "group___probe_calibration.html", null ],
    [ "Doppler", "group___doppler.html", "group___doppler" ],
    [ "Service", "group___service.html", "group___service" ],
    [ "Settings", "group___settings.html", "group___settings" ],
    [ "Coloring", "group___coloring.html", "group___coloring" ],
    [ "Camera", "group___camera.html", "group___camera" ],
    [ "Helper function", "group___helper.html", "group___helper" ],
    [ "Buffer", "group___buffer.html", "group___buffer" ],
    [ "Output Values (digital or analog)", "group___output_values.html", "group___output_values" ],
    [ "File Handling", "group__filehandling.html", "group__filehandling" ],
    [ "External trigger", "group___external_trigger.html", "group___external_trigger" ],
    [ "Post Processing", "group___post_processing.html", "group___post_processing" ],
    [ "Polarization", "group___polarization.html", "group___polarization" ],
    [ "Polarization Adjustment", "group___polarization_adjustment.html", "group___polarization_adjustment" ],
    [ "Reference Intensity Control", "group___ref_int_control.html", "group___ref_int_control" ],
    [ "Amplification Control", "group___amplification_control.html", "group___amplification_control" ]
];